### ISSUE TITLE
token sent issue

### ISSUE THREAD

**Issue by manking698** [merigo-labs/solana-web3#1]
Hi , may check how to send token? been try this but it failed, it prompt error
[JsonRpcException<dynamic>] -32002 : Transaction simulation failed: This program may not be used for executing instructions

     var instruction = SolanaWeb3.TransactionInstruction(keys: [
        SolanaWeb3.AccountMeta(
          senderIDx,
          isSigner: true,
          isWritable: true,
        )
      ], programId: programId1);

      //final solTransaction = SolanaWeb3.Transaction();

      final transaction = SolanaWeb3.Transaction(
          feePayer: senderIDx,
          recentBlockhash: (await connection.getLatestBlockhash()).blockhash);
      transaction.add(instruction);
      transaction.add(SystemProgram.transfer(
          fromPublicKey: senderIDx,
          toPublicKey: receiver1,
          lamports: SolanaWeb3.solToLamports(1)));

      String tx1 = await connection
          .sendAndConfirmTransaction(transaction, signers: [walletSolana]);

**Comment by merigo-labs** [comment]
Hi @manking502,

I should be able to help you with this.

How did you generate `senderIDx`?

If `senderIDx` is a Keypair, you could try the following:
```
// Your keypair
final senderIDx = Keypair.generate();

// Create transaction
final tx = Transaction();

// Add transfer instruction
tx.add(
    SystemProgram.transfer(
        fromPublicKey: senderIDx.publicKey, 
        toPublicKey: receiver1, 
        lamports: SolanaWeb3.solToLamports(1),
    )
);

// Send transaction to cluster and wait for confirmation.
String signature = await connection.sendAndConfirmTransaction(tx, signers: [senderIDx]);
```
